### ISSUE TITLE
Error when trying to sign after changing content

### ISSUE THREAD

**Issue by KillTrot** [AbdurazaaqMohammed/AntiSplit-M#5]
If I do changes in the Smali Files of the APK, for example with ReVanced, the process of patching with revanced fails with the following error:

```
com.android.apksig.apk.MinSdkVersionException: Failed to determine APK's minimum supported Android platform version
        at com.android.apksig.ApkSigner.getMinSdkVersionFromApk(ApkSigner.java:1006)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:295)
        at com.android.apksig.ApkSigner.sign(ApkSigner.java:231)
        at app.revanced.library.ApkSigner$Signer.signApk(ApkSigner.kt:337)
        at app.revanced.library.ApkUtils.signApk(ApkUtils.kt:169)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:321)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: com.android.apksig.zip.ZipFormatException: Data Descriptor presence mismatch between Local File Header and Central Directory for entry AndroidManifest.xml. LFH: true, CD: false
        at com.android.apksig.internal.zip.LocalFileRecord.getRecord(LocalFileRecord.java:180)
        at com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(LocalFileRecord.java:427)
        at com.android.apksig.internal.zip.LocalFileRecord.getUncompressedData(LocalFileRecord.java:451)
        at com.android.apksig.ApkSigner.getAndroidManifestFromApk(ApkSigner.java:966)
        at com.android.apksig.ApkSigner.getMinSdkVersionFromApk(ApkSigner.java:1004)
```

I'm specifically trying to do it with the xapk from here:
[https://apkpure.com/swissid/com.swisssign.swissid.mobile](https://apkpure.com/swissid/com.swisssign.swissid.mobile)

Any idea what is wrong or what I am doing wrong?

**Comment by AbdurazaaqMohammed** [comment]
You are not doing anything wrong, the issue is in apksig. The easiest way to fix this is to download [ReVanced Manager with that error removed](https://github.com/AbdurazaaqMohammed/revanced-antisplit).
